import { useMemo, useState } from 'react';
import MonthlyGrowthChart from '../components/MonthlyGrowthChart';
import RecentActivity from '../components/RecentActivity';
import StatusBadge from '../components/StatusBadge';
import ContributionFormDialog from '../components/ContributionFormDialog';
import { formatMoney, getMonthlyGrowth, getRecentActivity, getMemberById } from '../lib/fundUtils';
import { getAttentionItems, getFundBreakdown, getMonthlyHealth, memberStreak, reminderText } from '../lib/featureUtils';

export default function DashboardPage({members,contributions,withdrawals,auditTrail,settings,currentUser,onGoToPage,onRefresh,onSubmitContribution,isSubmitting}){
 const [showBreakdown,setShowBreakdown]=useState(false); const [showContributionForm,setShowContributionForm]=useState(false); const health=getMonthlyHealth(members,contributions); const breakdown=getFundBreakdown(contributions,withdrawals); const attention=getAttentionItems(members,contributions,withdrawals); const growth=getMonthlyGrowth(contributions,withdrawals,settings.start_date); const activity=getRecentActivity(members,contributions,withdrawals,auditTrail,8); const active=members.filter(m=>m.role==='member');
 const paidCount=health.rows.filter(r=>r.status==='paid').length, partialCount=health.rows.filter(r=>r.status==='partial').length;
 const pendingTotal=breakdown.pendingWithdrawals;
 async function copyReminder(row){await navigator.clipboard.writeText(reminderText(row.member,settings.currency,row.owed));window.alert(`Reminder copied for ${row.member.name}.`)}
 return <div className="page-stack">
  {!currentUser || currentUser.role==='admin' ? null : <section className="payment-cta card-section">
   <div><p className="eyebrow">Your contribution</p><h2>Have you made your contribution?</h2><p className="muted">Record the amount you paid. The administrator will verify it before it is added to the fund balance.</p></div>
   <button className="primary-button" onClick={()=>setShowContributionForm(true)}>Submit Contribution</button>
  </section>}
  <section className="snapshot-card"><div><p className="eyebrow">Fund snapshot</p><h2>{settings.fund_name}</h2><button className="balance-button" onClick={()=>setShowBreakdown(!showBreakdown)}><strong>{formatMoney(breakdown.balance,settings.currency)}</strong><span>Current fund balance · click for breakdown</span></button></div><div className="snapshot-side"><span className="mini-label">This month</span><strong>{formatMoney(health.collected,settings.currency)}</strong><span>of {formatMoney(health.expected,settings.currency)} collected</span></div></section>
  {showBreakdown&&<section className="card-section breakdown-grid"><div><span>Total contributions</span><strong>{formatMoney(breakdown.totalContributions,settings.currency)}</strong></div><div><span>Approved withdrawals</span><strong>{formatMoney(breakdown.approvedWithdrawals,settings.currency)}</strong></div><div><span>Pending withdrawals</span><strong>{formatMoney(breakdown.pendingWithdrawals,settings.currency)}</strong></div><div><span>Available balance</span><strong>{formatMoney(breakdown.balance,settings.currency)}</strong></div></section>}
  <section className="monthly-health card-section"><div className="section-heading"><div><p className="eyebrow">Monthly fund health</p><h2>Contribution progress</h2></div><strong>{Math.round(health.percent)}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${health.percent}%`}}/></div><div className="health-stats"><span><b>{formatMoney(health.collected,settings.currency)}</b> collected</span><span><b>{formatMoney(health.outstanding,settings.currency)}</b> outstanding</span><span><b>{paidCount}</b> paid · <b>{partialCount}</b> partial · <b>{health.rows.filter(r=>r.owed>0&&r.status==='outstanding').length}</b> unpaid</span></div></section>
  <section className="attention-card card-section"><div className="section-heading"><div><p className="eyebrow">Action centre</p><h2>Needs attention</h2></div></div><div className="attention-grid">{attention.map(item=><button key={item.key} className={`attention-item ${item.type}`} onClick={()=>onGoToPage(item.key==='withdrawals'?'withdrawals':'contributions')}><strong>{item.title}</strong><span>{item.detail}</span></button>)}</div></section>
  {active.length>0&&<section className="card-section"><div className="section-heading"><div><p className="eyebrow">Consistency</p><h2>Member contribution record</h2></div></div><div className="member-health-grid">{active.map(m=>{const row=health.rows.find(r=>r.member.id===m.id);const streak=memberStreak(m,contributions);return <div className="member-health" key={m.id}><div><strong>{m.name}</strong><StatusBadge status={row?.status}/></div><span>{formatMoney(row?.paid||0,settings.currency)} / {formatMoney(m.monthly_target,settings.currency)} this month</span><small>{streak} month{streak===1?'':'s'} consecutive full payment</small>{row?.owed>0&&<button className="link-button" onClick={()=>copyReminder(row)}>Copy reminder</button>}</div>})}</div></section>}
  <MonthlyGrowthChart data={growth} currency={settings.currency}/>
  <div className="two-column-grid"><RecentActivity items={activity} currency={settings.currency}/><section className="card-section"><div className="section-heading"><div><p className="eyebrow">Withdrawal control</p><h2>Requests</h2></div><button className="secondary-button compact" onClick={()=>onGoToPage('withdrawals')}>View all</button></div><div className="summary-list"><div><span>Pending</span><strong>{formatMoney(pendingTotal,settings.currency)}</strong></div><div><span>Approved</span><strong>{formatMoney(breakdown.approvedWithdrawals,settings.currency)}</strong></div><div><span>Members</span><strong>{active.length}</strong></div></div></section></div>
  {showContributionForm ? <ContributionFormDialog members={members} currentUser={currentUser} mode="member" onClose={()=>setShowContributionForm(false)} onSubmit={(payload)=>{onSubmitContribution(payload);setShowContributionForm(false);}} isSubmitting={isSubmitting} /> : null}
 </div>
}
